### ISSUE TITLE
Whole day data - how would I change the x axis to date

### ISSUE THREAD

**Issue by cretace** [denisemauldin/d3-timeline#10]
Doing a sort of Gantt chart but my data is in blocks of days. 
I'm getting there but any idea how I change x axis to show date not times? Even zooming out I still see times.
Hmm ok.. I see the axis does not redraw on zoom.
This one does: 
https://github.com/commodityvectors/d3-timeline
..scratch head.. 
anyway thanks for your code

**Comment by sharepointmike** [comment]
@cretace @denisemauldin 
I have the same question. I would like to use dates instead of times. Can someone help me out how to change the code?
Would very much appreciate

**Comment by cretace** [comment]
Hey -I gave up with d3 - dozens of annoying issues. Zoom limits were impossible to specfiy. Moved to Flot and all works much better - still (unix)time based but not hard to make it only do days.

**Comment by sharepointmike** [comment]
Thanks for your answer.
I try to create a, fairly, simple timeline without zooming. So I try to get it working in d3. I use c3.js for the simple charts, so I already have d3 in place. I general I would prefer to stick to that.

**Comment by denisemauldin** [comment]
@sharepointmike Are you using d3 version 4?

**Comment by sharepointmike** [comment]
Hi @denisemauldin, version 4. What I try now is converting my dates to Unix times and changing the format. Would that be the way to go?

**Comment by denisemauldin** [comment]
@sharepointmike Yes, this is designed to work with unix times in a relative way. Unfortunately this is not meant to display via days, but you might be able to find a tickFormat that would work.

**Comment by sharepointmike** [comment]
@denisemauldin this format: d3.timeFormat("%d-%m-%y") seems to work. 
Another question, I have a data set with a lot of "rows" It only shows me the first 5. Is there a limit somewhere?
