### ISSUE TITLE
scrolling boundary is off

### ISSUE THREAD

**Issue by peterhoth** [denisemauldin/d3-timeline#16]
In the scrollable.html example, when you move the timeline, it goes beyond the labels as shown in the image below. The scrollable boundary should start after the end of the longest captions.

![image](https://user-images.githubusercontent.com/7699250/40484839-7683ed44-5f8f-11e8-9640-353928619ae7.png)

**Comment by denisemauldin** [comment]
@peterhoth That's not how the original was built unfortunately.  I'd be happy to accept a PR to change this functionality, but for right now it's working as intended.
