### ISSUE TITLE
Change size of displayed circles

### ISSUE THREAD

**Issue by ksg20** [denisemauldin/d3-timeline#28]
I'm using the circles places on top the the rectangles to mark events in time on the timeline. I would like to reduce the size of the circle so that it doesn't take up as much space on the rectangle. I've tried changing the size using `transform: scale()` and `transform-origin: center` but it messes with the position of the circle on the timeline. Is there any way to do this? Thanks!

**Comment by denisemauldin** [comment]
@ksg20 It uses `itemHeight` to set the radius of the circle.

**Comment by ksg20** [comment]
Using `itemHeight` adjusts all of the data on the chart, not just the circles and using it individually on the circle's data has no effect.

I was able to change the circle size while keeping the position by using jQuery to adjust the `radius` property on the circles.
